import { Darumadrop_One, Hubballi, Afacad } from 'next/font/google'

import type { Metadata } from "next";
import Header from '@/components/Header';
import back from '../../public/background.svg';
import "./globals.css";

export const daruma_one = Darumadrop_One({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-daruma'
})

export const hubballi = Hubballi({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-hubballi'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${daruma_one.variable} ${hubballi.variable} bg-white min-h-dvh `} style={{ backgroundImage: `url('/test.svg')`, backgroundColor: '#F7F4E3', backgroundSize: "contain", backgroundPosition: "center" }}>
        <Header />
        <div id="root" >
          <div >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
